spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      # swagger的配置
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zxc.eldenmall.entity
